<fieldset class="form-list">
	<?php $_code=$this->getMethodCode() ?>
</fieldset>
<div id="payment_form_<?php echo $_code ?>" style="display:none;">
<p class="a-center"><img src="<?php echo $this->getSkinUrl('images/bancomer/bancomer_logo.gif') ?>" border="0" />
<br/>
<?php echo $this->__('Clicking on continue will refer you to the payment gateway of BBVA. Data from credit card is not stored on our servers.') ?>
</p>
</div>